name: Test modules

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Test Command
        run: go test -v ./command/
      - name: Test Parser
        run: go test -v ./parser/
      - name: Test Server
        run: go test -v ./server/
